---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  annotations:
    fluxcd.io/automated: "true"
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      module: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        module: webapp
    spec:
      serviceAccountName: default
      securityContext: {}
      containers:
      - name: webapp
        securityContext: {}
        image: alpine:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: p-abe-app
        command:
        - /bin/sh
        - -c
        - --
      dnsConfig:
        options:
        - name: ndots
          value: "1"

